### ISSUE TITLE
Add LoggerProvider

### ISSUE THREAD

**Issue by jongotlin** [jandreasn/an-sms#5]
On a development environment you don't always want to send real sms. I suggest adding a LoggerProvider which logs the text to a provided `Psr\Log\LoggerInterface`.

**Comment by andreasnij** [comment]
There is a `NullGateway` that is intended for just that. Would that work for your case?
```
$smsTransceiver = new SmsTransceiver(new NullGateway(), $debugLogger);
```

**Comment by jongotlin** [comment]
Awesome! Missed that one. Thanks
